#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Big_Driver

#include "Basic.hpp"

#include "ABPT_Driver_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_Big_Driver.ABP_Big_Driver_C
// 0x0000 (0x5BD0 - 0x5BD0)
class UABP_Big_Driver_C final : public UABPT_Driver_C
{
public:
	void GetLinkedAnimClass(class UClass** Out_AnimInstance);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ABP_Big_Driver_C">();
	}
	static class UABP_Big_Driver_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_Big_Driver_C>();
	}
};
static_assert(alignof(UABP_Big_Driver_C) == 0x000010, "Wrong alignment on UABP_Big_Driver_C");
static_assert(sizeof(UABP_Big_Driver_C) == 0x005BD0, "Wrong size on UABP_Big_Driver_C");

}

