#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GhostResultUploadActor

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UnionSystem_structs.hpp"


namespace SDK::Params
{

// Function BP_GhostResultUploadActor.BP_GhostResultUploadActor_C.Create Network Error Window
// 0x00C0 (0x00C0 - 0x0000)
struct BP_GhostResultUploadActor_C_Create_Network_Error_Window final
{
public:
	EResponseCodeAbstract                         ResponseCode;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetServerErrorTitleText_ReturnValue;      // 0x0008(0x0010)(ConstParm)
	class FText                                   CallFunc_GetServerErrorBodyText_ReturnValue;       // 0x0018(0x0010)()
	TDelegate<void(class UUnionUIButtonBase* Button, int32 PanelIndex, int32 ButtonIndex)> K2Node_CreateDelegate_OutputDelegate; // 0x0028(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue;              // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUnionUIPopupWindowManager*             CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue;               // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUnionUIPopupWindowBase*                CallFunc_CreatePopupWindow_ReturnValue;            // 0x0058(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IMenuPopupWindowInterface> K2Node_DynamicCast_AsMenu_Popup_Window_Interface; // 0x0060(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_71[0x7];                                       // 0x0071(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IMenuPopupWindowInterface> K2Node_DynamicCast_AsMenu_Popup_Window_Interface_1; // 0x0078(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_89[0x7];                                       // 0x0089(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IMenuPopupWindowInterface> K2Node_DynamicCast_AsMenu_Popup_Window_Interface_2; // 0x0090(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A1[0x7];                                       // 0x00A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IMenuPopupWindowInterface> K2Node_DynamicCast_AsMenu_Popup_Window_Interface_3; // 0x00A8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GhostResultUploadActor_C_Create_Network_Error_Window) == 0x000008, "Wrong alignment on BP_GhostResultUploadActor_C_Create_Network_Error_Window");
static_assert(sizeof(BP_GhostResultUploadActor_C_Create_Network_Error_Window) == 0x0000C0, "Wrong size on BP_GhostResultUploadActor_C_Create_Network_Error_Window");
static_assert(offsetof(BP_GhostResultUploadActor_C_Create_Network_Error_Window, ResponseCode) == 0x000000, "Member 'BP_GhostResultUploadActor_C_Create_Network_Error_Window::ResponseCode' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_Create_Network_Error_Window, CallFunc_GetServerErrorTitleText_ReturnValue) == 0x000008, "Member 'BP_GhostResultUploadActor_C_Create_Network_Error_Window::CallFunc_GetServerErrorTitleText_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_Create_Network_Error_Window, CallFunc_GetServerErrorBodyText_ReturnValue) == 0x000018, "Member 'BP_GhostResultUploadActor_C_Create_Network_Error_Window::CallFunc_GetServerErrorBodyText_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_Create_Network_Error_Window, K2Node_CreateDelegate_OutputDelegate) == 0x000028, "Member 'BP_GhostResultUploadActor_C_Create_Network_Error_Window::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_Create_Network_Error_Window, CallFunc_MakeLiteralByte_ReturnValue) == 0x000038, "Member 'BP_GhostResultUploadActor_C_Create_Network_Error_Window::CallFunc_MakeLiteralByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_Create_Network_Error_Window, CallFunc_GetPlayerController_ReturnValue) == 0x000040, "Member 'BP_GhostResultUploadActor_C_Create_Network_Error_Window::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_Create_Network_Error_Window, CallFunc_GetGameInstanceSubsystem_ReturnValue) == 0x000048, "Member 'BP_GhostResultUploadActor_C_Create_Network_Error_Window::CallFunc_GetGameInstanceSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_Create_Network_Error_Window, CallFunc_Conv_ByteToInt_ReturnValue) == 0x000050, "Member 'BP_GhostResultUploadActor_C_Create_Network_Error_Window::CallFunc_Conv_ByteToInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_Create_Network_Error_Window, CallFunc_CreatePopupWindow_ReturnValue) == 0x000058, "Member 'BP_GhostResultUploadActor_C_Create_Network_Error_Window::CallFunc_CreatePopupWindow_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_Create_Network_Error_Window, K2Node_DynamicCast_AsMenu_Popup_Window_Interface) == 0x000060, "Member 'BP_GhostResultUploadActor_C_Create_Network_Error_Window::K2Node_DynamicCast_AsMenu_Popup_Window_Interface' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_Create_Network_Error_Window, K2Node_DynamicCast_bSuccess) == 0x000070, "Member 'BP_GhostResultUploadActor_C_Create_Network_Error_Window::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_Create_Network_Error_Window, K2Node_DynamicCast_AsMenu_Popup_Window_Interface_1) == 0x000078, "Member 'BP_GhostResultUploadActor_C_Create_Network_Error_Window::K2Node_DynamicCast_AsMenu_Popup_Window_Interface_1' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_Create_Network_Error_Window, K2Node_DynamicCast_bSuccess_1) == 0x000088, "Member 'BP_GhostResultUploadActor_C_Create_Network_Error_Window::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_Create_Network_Error_Window, K2Node_DynamicCast_AsMenu_Popup_Window_Interface_2) == 0x000090, "Member 'BP_GhostResultUploadActor_C_Create_Network_Error_Window::K2Node_DynamicCast_AsMenu_Popup_Window_Interface_2' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_Create_Network_Error_Window, K2Node_DynamicCast_bSuccess_2) == 0x0000A0, "Member 'BP_GhostResultUploadActor_C_Create_Network_Error_Window::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_Create_Network_Error_Window, K2Node_DynamicCast_AsMenu_Popup_Window_Interface_3) == 0x0000A8, "Member 'BP_GhostResultUploadActor_C_Create_Network_Error_Window::K2Node_DynamicCast_AsMenu_Popup_Window_Interface_3' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_Create_Network_Error_Window, K2Node_DynamicCast_bSuccess_3) == 0x0000B8, "Member 'BP_GhostResultUploadActor_C_Create_Network_Error_Window::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");

// Function BP_GhostResultUploadActor.BP_GhostResultUploadActor_C.CreateErrorWindow
// 0x00B8 (0x00B8 - 0x0000)
struct BP_GhostResultUploadActor_C_CreateErrorWindow final
{
public:
	class FText                                   MessageText;                                       // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	TDelegate<void(class UUnionUIButtonBase* Button, int32 PanelIndex, int32 ButtonIndex)> K2Node_CreateDelegate_OutputDelegate; // 0x0010(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue;              // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUnionUIPopupWindowManager*             CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue;               // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUnionUIPopupWindowBase*                CallFunc_CreatePopupWindow_ReturnValue;            // 0x0040(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_MakeLiteralText_ReturnValue;              // 0x0048(0x0010)()
	TScriptInterface<class IMenuPopupWindowInterface> K2Node_DynamicCast_AsMenu_Popup_Window_Interface; // 0x0058(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_69[0x7];                                       // 0x0069(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IMenuPopupWindowInterface> K2Node_DynamicCast_AsMenu_Popup_Window_Interface_1; // 0x0070(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_81[0x7];                                       // 0x0081(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IMenuPopupWindowInterface> K2Node_DynamicCast_AsMenu_Popup_Window_Interface_2; // 0x0088(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_99[0x7];                                       // 0x0099(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IMenuPopupWindowInterface> K2Node_DynamicCast_AsMenu_Popup_Window_Interface_3; // 0x00A0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GhostResultUploadActor_C_CreateErrorWindow) == 0x000008, "Wrong alignment on BP_GhostResultUploadActor_C_CreateErrorWindow");
static_assert(sizeof(BP_GhostResultUploadActor_C_CreateErrorWindow) == 0x0000B8, "Wrong size on BP_GhostResultUploadActor_C_CreateErrorWindow");
static_assert(offsetof(BP_GhostResultUploadActor_C_CreateErrorWindow, MessageText) == 0x000000, "Member 'BP_GhostResultUploadActor_C_CreateErrorWindow::MessageText' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_CreateErrorWindow, K2Node_CreateDelegate_OutputDelegate) == 0x000010, "Member 'BP_GhostResultUploadActor_C_CreateErrorWindow::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_CreateErrorWindow, CallFunc_MakeLiteralByte_ReturnValue) == 0x000020, "Member 'BP_GhostResultUploadActor_C_CreateErrorWindow::CallFunc_MakeLiteralByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_CreateErrorWindow, CallFunc_GetPlayerController_ReturnValue) == 0x000028, "Member 'BP_GhostResultUploadActor_C_CreateErrorWindow::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_CreateErrorWindow, CallFunc_GetGameInstanceSubsystem_ReturnValue) == 0x000030, "Member 'BP_GhostResultUploadActor_C_CreateErrorWindow::CallFunc_GetGameInstanceSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_CreateErrorWindow, CallFunc_Conv_ByteToInt_ReturnValue) == 0x000038, "Member 'BP_GhostResultUploadActor_C_CreateErrorWindow::CallFunc_Conv_ByteToInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_CreateErrorWindow, CallFunc_CreatePopupWindow_ReturnValue) == 0x000040, "Member 'BP_GhostResultUploadActor_C_CreateErrorWindow::CallFunc_CreatePopupWindow_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_CreateErrorWindow, CallFunc_MakeLiteralText_ReturnValue) == 0x000048, "Member 'BP_GhostResultUploadActor_C_CreateErrorWindow::CallFunc_MakeLiteralText_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_CreateErrorWindow, K2Node_DynamicCast_AsMenu_Popup_Window_Interface) == 0x000058, "Member 'BP_GhostResultUploadActor_C_CreateErrorWindow::K2Node_DynamicCast_AsMenu_Popup_Window_Interface' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_CreateErrorWindow, K2Node_DynamicCast_bSuccess) == 0x000068, "Member 'BP_GhostResultUploadActor_C_CreateErrorWindow::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_CreateErrorWindow, K2Node_DynamicCast_AsMenu_Popup_Window_Interface_1) == 0x000070, "Member 'BP_GhostResultUploadActor_C_CreateErrorWindow::K2Node_DynamicCast_AsMenu_Popup_Window_Interface_1' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_CreateErrorWindow, K2Node_DynamicCast_bSuccess_1) == 0x000080, "Member 'BP_GhostResultUploadActor_C_CreateErrorWindow::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_CreateErrorWindow, K2Node_DynamicCast_AsMenu_Popup_Window_Interface_2) == 0x000088, "Member 'BP_GhostResultUploadActor_C_CreateErrorWindow::K2Node_DynamicCast_AsMenu_Popup_Window_Interface_2' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_CreateErrorWindow, K2Node_DynamicCast_bSuccess_2) == 0x000098, "Member 'BP_GhostResultUploadActor_C_CreateErrorWindow::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_CreateErrorWindow, K2Node_DynamicCast_AsMenu_Popup_Window_Interface_3) == 0x0000A0, "Member 'BP_GhostResultUploadActor_C_CreateErrorWindow::K2Node_DynamicCast_AsMenu_Popup_Window_Interface_3' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_CreateErrorWindow, K2Node_DynamicCast_bSuccess_3) == 0x0000B0, "Member 'BP_GhostResultUploadActor_C_CreateErrorWindow::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");

// Function BP_GhostResultUploadActor.BP_GhostResultUploadActor_C.ExecuteUbergraph_BP_GhostResultUploadActor
// 0x0230 (0x0230 - 0x0000)
struct BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UGhostDataController*                   CallFunc_SpawnObject_ReturnValue;                  // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMenuWorldSubsystem*                    CallFunc_GetWorldSubsystem_ReturnValue;            // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UMenuWorldSubsystem*                    CallFunc_GetWorldSubsystem_ReturnValue_1;          // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x002A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x002B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x002C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2D[0x3];                                       // 0x002D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_FooterMenu_C*                      CallFunc_Create_ReturnValue;                       // 0x0030(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UMenuWorldSubsystem*                    CallFunc_GetWorldSubsystem_ReturnValue_2;          // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_5;                    // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_6;                    // 0x0041(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_42[0x6];                                       // 0x0042(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UMenuWorldSubsystem*                    CallFunc_GetWorldSubsystem_ReturnValue_3;          // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_7;                    // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_8;                    // 0x0051(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_52[0x6];                                       // 0x0052(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UForceNextSequenceManagerSubsytem*      CallFunc_GetWorldSubsystem_ReturnValue_4;          // 0x0058(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CancelUpload_ReturnValue;                 // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable; // 0x0061(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_IsError;                        // 0x0062(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EUploadState                                  K2Node_CustomEvent_UploadState;                    // 0x0063(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_64[0x4];                                       // 0x0064(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUnionUIButtonBase*                     K2Node_CustomEvent_Button;                         // 0x0068(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_PanelIndex;                     // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_ButtonIndex;                    // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0078(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(bool IsError, EUploadState UploadState)> K2Node_CreateDelegate_OutputDelegate_1;  // 0x0088(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetUploadMaxCount_ReturnValue;            // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetUploadCount_ReturnValue;               // 0x009C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UForceNextSequenceManagerSubsytem*      CallFunc_GetWorldSubsystem_ReturnValue_5;          // 0x00A0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_9;                    // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A9[0x3];                                       // 0x00A9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x00AC(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(bool IsError, EUploadState UploadState)> K2Node_CreateDelegate_OutputDelegate_3;  // 0x00BC(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_4;            // 0x00CC(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FSoundHandle                           CallFunc_SoundPlay_ReturnValue;                    // 0x00DC(0x0004)()
	bool                                          CallFunc_IsValid_ReturnValue_10;                   // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_11;                   // 0x00E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EResponseCodeAbstract                         CallFunc_GetResponseCode_ReturnValue;              // 0x00E2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E3[0x1];                                       // 0x00E3(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Event_DeltaSeconds;                         // 0x00E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E9[0x3];                                       // 0x00E9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetUploadRate_ReturnValue;                // 0x00EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x00F0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_12;                   // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F9[0x7];                                       // 0x00F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AAppPlayerController*                   K2Node_DynamicCast_AsApp_Player_Controller;        // 0x0100(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_109[0x7];                                      // 0x0109(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_1;        // 0x0110(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AAppPlayerController*                   K2Node_DynamicCast_AsApp_Player_Controller_1;      // 0x0118(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0120(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_UnregisterSingleSubMenu_ReturnValue;      // 0x0121(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_122[0x2];                                      // 0x0122(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class UObject* Object)>        K2Node_CreateDelegate_OutputDelegate_5;            // 0x0124(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_134[0x4];                                      // 0x0134(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                K2Node_CustomEvent_Object;                         // 0x0138(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_13;                   // 0x0140(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_141[0x3];                                      // 0x0141(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class UObject* Object)>        K2Node_CreateDelegate_OutputDelegate_6;            // 0x0144(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_14;                   // 0x0154(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_15;                   // 0x0155(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0156(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_157[0x1];                                      // 0x0157(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class UObject* Object)>        K2Node_CreateDelegate_OutputDelegate_7;            // 0x0158(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_16;                   // 0x0168(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0169(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EEndPlayReason                                K2Node_Event_EndPlayReason;                        // 0x016A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_16B[0x5];                                      // 0x016B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class USoundAtomCue*                          Temp_object_Variable;                              // 0x0170(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_17;                   // 0x0178(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_179[0x7];                                      // 0x0179(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USoundAtomCue*                          Temp_object_Variable_1;                            // 0x0180(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_ReturnValue;             // 0x0188(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsBusy_ReturnValue;                       // 0x0190(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x0191(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x0192(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x0193(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_DoubleDouble_ReturnValue;    // 0x0194(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0195(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_196[0x2];                                      // 0x0196(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class USoundAtomCue*                          K2Node_Select_Default;                             // 0x0198(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FSoundHandle                           CallFunc_SoundPlay_ReturnValue_1;                  // 0x01A0(0x0004)()
	uint8                                         Pad_1A4[0x4];                                      // 0x01A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_MakeLiteralText_ReturnValue;              // 0x01A8(0x0010)()
	class FText                                   CallFunc_MakeLiteralText_ReturnValue_1;            // 0x01B8(0x0010)()
	class FText                                   K2Node_Select_Default_1;                           // 0x01C8(0x0010)(ConstParm)
	class FText                                   CallFunc_MakeLiteralText_ReturnValue_2;            // 0x01D8(0x0010)()
	bool                                          CallFunc_IsResponceCheat_ReturnValue;              // 0x01E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1E9[0x7];                                      // 0x01E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_MakeLiteralText_ReturnValue_3;            // 0x01F0(0x0010)()
	bool                                          CallFunc_IsValid_ReturnValue_18;                   // 0x0200(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_201[0x7];                                      // 0x0201(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMenuInputRecieveObject*                CallFunc_SpawnObject_ReturnValue_1;                // 0x0208(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UUnionUIButtonBase* Button, int32 PanelIndex, int32 ButtonIndex)> K2Node_CreateDelegate_OutputDelegate_8; // 0x0210(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_B_ImplicitCast;          // 0x0220(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_SetUploadPercentage_InRate_ImplicitCast;  // 0x0228(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor) == 0x000008, "Wrong alignment on BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor");
static_assert(sizeof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor) == 0x000230, "Wrong size on BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, EntryPoint) == 0x000000, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_SpawnObject_ReturnValue) == 0x000008, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_SpawnObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_IsValid_ReturnValue) == 0x000010, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_GetWorldSubsystem_ReturnValue) == 0x000018, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_GetWorldSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_GetWorldSubsystem_ReturnValue_1) == 0x000020, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_GetWorldSubsystem_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_IsValid_ReturnValue_1) == 0x000028, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_IsValid_ReturnValue_2) == 0x000029, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_IsValid_ReturnValue_3) == 0x00002A, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_IsValid_ReturnValue_4) == 0x00002B, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_IsValid_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, Temp_bool_Variable) == 0x00002C, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_Create_ReturnValue) == 0x000030, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_GetWorldSubsystem_ReturnValue_2) == 0x000038, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_GetWorldSubsystem_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_IsValid_ReturnValue_5) == 0x000040, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_IsValid_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_IsValid_ReturnValue_6) == 0x000041, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_IsValid_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_GetWorldSubsystem_ReturnValue_3) == 0x000048, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_GetWorldSubsystem_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_IsValid_ReturnValue_7) == 0x000050, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_IsValid_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_IsValid_ReturnValue_8) == 0x000051, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_IsValid_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_GetWorldSubsystem_ReturnValue_4) == 0x000058, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_GetWorldSubsystem_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_CancelUpload_ReturnValue) == 0x000060, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_CancelUpload_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable) == 0x000061, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, K2Node_CustomEvent_IsError) == 0x000062, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::K2Node_CustomEvent_IsError' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, K2Node_CustomEvent_UploadState) == 0x000063, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::K2Node_CustomEvent_UploadState' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, K2Node_CustomEvent_Button) == 0x000068, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::K2Node_CustomEvent_Button' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, K2Node_CustomEvent_PanelIndex) == 0x000070, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::K2Node_CustomEvent_PanelIndex' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, K2Node_CustomEvent_ButtonIndex) == 0x000074, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::K2Node_CustomEvent_ButtonIndex' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, K2Node_CreateDelegate_OutputDelegate) == 0x000078, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, K2Node_CreateDelegate_OutputDelegate_1) == 0x000088, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_GetUploadMaxCount_ReturnValue) == 0x000098, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_GetUploadMaxCount_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_GetUploadCount_ReturnValue) == 0x00009C, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_GetUploadCount_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_GetWorldSubsystem_ReturnValue_5) == 0x0000A0, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_GetWorldSubsystem_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_IsValid_ReturnValue_9) == 0x0000A8, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_IsValid_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, K2Node_CreateDelegate_OutputDelegate_2) == 0x0000AC, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, K2Node_CreateDelegate_OutputDelegate_3) == 0x0000BC, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, K2Node_CreateDelegate_OutputDelegate_4) == 0x0000CC, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_SoundPlay_ReturnValue) == 0x0000DC, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_SoundPlay_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_IsValid_ReturnValue_10) == 0x0000E0, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_IsValid_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_IsValid_ReturnValue_11) == 0x0000E1, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_IsValid_ReturnValue_11' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_GetResponseCode_ReturnValue) == 0x0000E2, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_GetResponseCode_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, K2Node_Event_DeltaSeconds) == 0x0000E4, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_Not_PreBool_ReturnValue) == 0x0000E8, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_GetUploadRate_ReturnValue) == 0x0000EC, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_GetUploadRate_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_GetPlayerController_ReturnValue) == 0x0000F0, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_IsValid_ReturnValue_12) == 0x0000F8, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_IsValid_ReturnValue_12' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, K2Node_DynamicCast_AsApp_Player_Controller) == 0x000100, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::K2Node_DynamicCast_AsApp_Player_Controller' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, K2Node_DynamicCast_bSuccess) == 0x000108, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_GetPlayerController_ReturnValue_1) == 0x000110, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_GetPlayerController_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, K2Node_DynamicCast_AsApp_Player_Controller_1) == 0x000118, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::K2Node_DynamicCast_AsApp_Player_Controller_1' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, K2Node_DynamicCast_bSuccess_1) == 0x000120, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_UnregisterSingleSubMenu_ReturnValue) == 0x000121, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_UnregisterSingleSubMenu_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, K2Node_CreateDelegate_OutputDelegate_5) == 0x000124, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::K2Node_CreateDelegate_OutputDelegate_5' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, K2Node_CustomEvent_Object) == 0x000138, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::K2Node_CustomEvent_Object' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_IsValid_ReturnValue_13) == 0x000140, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_IsValid_ReturnValue_13' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, K2Node_CreateDelegate_OutputDelegate_6) == 0x000144, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::K2Node_CreateDelegate_OutputDelegate_6' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_IsValid_ReturnValue_14) == 0x000154, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_IsValid_ReturnValue_14' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_IsValid_ReturnValue_15) == 0x000155, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_IsValid_ReturnValue_15' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_BooleanAND_ReturnValue) == 0x000156, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, K2Node_CreateDelegate_OutputDelegate_7) == 0x000158, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::K2Node_CreateDelegate_OutputDelegate_7' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_IsValid_ReturnValue_16) == 0x000168, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_IsValid_ReturnValue_16' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, Temp_bool_Has_Been_Initd_Variable) == 0x000169, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, K2Node_Event_EndPlayReason) == 0x00016A, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::K2Node_Event_EndPlayReason' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, Temp_object_Variable) == 0x000170, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_IsValid_ReturnValue_17) == 0x000178, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_IsValid_ReturnValue_17' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, Temp_object_Variable_1) == 0x000180, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::Temp_object_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_Add_DoubleDouble_ReturnValue) == 0x000188, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_Add_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_IsBusy_ReturnValue) == 0x000190, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_IsBusy_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, Temp_bool_IsClosed_Variable) == 0x000191, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_Not_PreBool_ReturnValue_1) == 0x000192, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_Not_PreBool_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_BooleanAND_ReturnValue_1) == 0x000193, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_GreaterEqual_DoubleDouble_ReturnValue) == 0x000194, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_GreaterEqual_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, Temp_bool_Variable_1) == 0x000195, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, K2Node_Select_Default) == 0x000198, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_SoundPlay_ReturnValue_1) == 0x0001A0, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_SoundPlay_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_MakeLiteralText_ReturnValue) == 0x0001A8, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_MakeLiteralText_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_MakeLiteralText_ReturnValue_1) == 0x0001B8, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_MakeLiteralText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, K2Node_Select_Default_1) == 0x0001C8, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_MakeLiteralText_ReturnValue_2) == 0x0001D8, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_MakeLiteralText_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_IsResponceCheat_ReturnValue) == 0x0001E8, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_IsResponceCheat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_MakeLiteralText_ReturnValue_3) == 0x0001F0, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_MakeLiteralText_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_IsValid_ReturnValue_18) == 0x000200, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_IsValid_ReturnValue_18' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_SpawnObject_ReturnValue_1) == 0x000208, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_SpawnObject_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, K2Node_CreateDelegate_OutputDelegate_8) == 0x000210, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::K2Node_CreateDelegate_OutputDelegate_8' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_Add_DoubleDouble_B_ImplicitCast) == 0x000220, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_Add_DoubleDouble_B_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor, CallFunc_SetUploadPercentage_InRate_ImplicitCast) == 0x000228, "Member 'BP_GhostResultUploadActor_C_ExecuteUbergraph_BP_GhostResultUploadActor::CallFunc_SetUploadPercentage_InRate_ImplicitCast' has a wrong offset!");

// Function BP_GhostResultUploadActor.BP_GhostResultUploadActor_C.OnCancelUpload
// 0x0008 (0x0008 - 0x0000)
struct BP_GhostResultUploadActor_C_OnCancelUpload final
{
public:
	class UObject*                                Object;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GhostResultUploadActor_C_OnCancelUpload) == 0x000008, "Wrong alignment on BP_GhostResultUploadActor_C_OnCancelUpload");
static_assert(sizeof(BP_GhostResultUploadActor_C_OnCancelUpload) == 0x000008, "Wrong size on BP_GhostResultUploadActor_C_OnCancelUpload");
static_assert(offsetof(BP_GhostResultUploadActor_C_OnCancelUpload, Object) == 0x000000, "Member 'BP_GhostResultUploadActor_C_OnCancelUpload::Object' has a wrong offset!");

// Function BP_GhostResultUploadActor.BP_GhostResultUploadActor_C.ReceiveEndPlay
// 0x0001 (0x0001 - 0x0000)
struct BP_GhostResultUploadActor_C_ReceiveEndPlay final
{
public:
	EEndPlayReason                                EndPlayReason;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GhostResultUploadActor_C_ReceiveEndPlay) == 0x000001, "Wrong alignment on BP_GhostResultUploadActor_C_ReceiveEndPlay");
static_assert(sizeof(BP_GhostResultUploadActor_C_ReceiveEndPlay) == 0x000001, "Wrong size on BP_GhostResultUploadActor_C_ReceiveEndPlay");
static_assert(offsetof(BP_GhostResultUploadActor_C_ReceiveEndPlay, EndPlayReason) == 0x000000, "Member 'BP_GhostResultUploadActor_C_ReceiveEndPlay::EndPlayReason' has a wrong offset!");

// Function BP_GhostResultUploadActor.BP_GhostResultUploadActor_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct BP_GhostResultUploadActor_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GhostResultUploadActor_C_ReceiveTick) == 0x000004, "Wrong alignment on BP_GhostResultUploadActor_C_ReceiveTick");
static_assert(sizeof(BP_GhostResultUploadActor_C_ReceiveTick) == 0x000004, "Wrong size on BP_GhostResultUploadActor_C_ReceiveTick");
static_assert(offsetof(BP_GhostResultUploadActor_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'BP_GhostResultUploadActor_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

// Function BP_GhostResultUploadActor.BP_GhostResultUploadActor_C.Setup All Upload
// 0x0030 (0x0030 - 0x0000)
struct BP_GhostResultUploadActor_C_Setup_All_Upload final
{
public:
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue;              // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<EStageId>                              CallFunc_FindStagesWithoutGhostUpload_ReturnValue; // 0x0008(0x0010)(ReferenceParm)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_1;            // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<EStageId>                              CallFunc_FindStagesWithoutGhostUpload_ReturnValue_1; // 0x0020(0x0010)(ReferenceParm)
};
static_assert(alignof(BP_GhostResultUploadActor_C_Setup_All_Upload) == 0x000008, "Wrong alignment on BP_GhostResultUploadActor_C_Setup_All_Upload");
static_assert(sizeof(BP_GhostResultUploadActor_C_Setup_All_Upload) == 0x000030, "Wrong size on BP_GhostResultUploadActor_C_Setup_All_Upload");
static_assert(offsetof(BP_GhostResultUploadActor_C_Setup_All_Upload, CallFunc_MakeLiteralByte_ReturnValue) == 0x000000, "Member 'BP_GhostResultUploadActor_C_Setup_All_Upload::CallFunc_MakeLiteralByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_Setup_All_Upload, CallFunc_FindStagesWithoutGhostUpload_ReturnValue) == 0x000008, "Member 'BP_GhostResultUploadActor_C_Setup_All_Upload::CallFunc_FindStagesWithoutGhostUpload_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_Setup_All_Upload, CallFunc_MakeLiteralByte_ReturnValue_1) == 0x000018, "Member 'BP_GhostResultUploadActor_C_Setup_All_Upload::CallFunc_MakeLiteralByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_Setup_All_Upload, CallFunc_FindStagesWithoutGhostUpload_ReturnValue_1) == 0x000020, "Member 'BP_GhostResultUploadActor_C_Setup_All_Upload::CallFunc_FindStagesWithoutGhostUpload_ReturnValue_1' has a wrong offset!");

// Function BP_GhostResultUploadActor.BP_GhostResultUploadActor_C.Setup Single Upload
// 0x0018 (0x0018 - 0x0000)
struct BP_GhostResultUploadActor_C_Setup_Single_Upload final
{
public:
	ESpeedClassId                                 InSpeedClassId;                                    // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EStageId                                      InStageId;                                         // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<EStageId>                              K2Node_MakeArray_Array;                            // 0x0008(0x0010)(ConstParm, ReferenceParm)
};
static_assert(alignof(BP_GhostResultUploadActor_C_Setup_Single_Upload) == 0x000008, "Wrong alignment on BP_GhostResultUploadActor_C_Setup_Single_Upload");
static_assert(sizeof(BP_GhostResultUploadActor_C_Setup_Single_Upload) == 0x000018, "Wrong size on BP_GhostResultUploadActor_C_Setup_Single_Upload");
static_assert(offsetof(BP_GhostResultUploadActor_C_Setup_Single_Upload, InSpeedClassId) == 0x000000, "Member 'BP_GhostResultUploadActor_C_Setup_Single_Upload::InSpeedClassId' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_Setup_Single_Upload, InStageId) == 0x000001, "Member 'BP_GhostResultUploadActor_C_Setup_Single_Upload::InStageId' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_Setup_Single_Upload, K2Node_MakeArray_Array) == 0x000008, "Member 'BP_GhostResultUploadActor_C_Setup_Single_Upload::K2Node_MakeArray_Array' has a wrong offset!");

// Function BP_GhostResultUploadActor.BP_GhostResultUploadActor_C.StartUpload
// 0x0088 (0x0088 - 0x0000)
struct BP_GhostResultUploadActor_C_StartUpload final
{
public:
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue;              // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_PrivateMatch_Popup_C*              CallFunc_Create_ReturnValue;                       // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue;               // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetTimeTrialCurrentStageVersion_ReturnValue; // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsUserHasNetworkRankingPrivilege_ReturnValue; // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_MakeLiteralText_ReturnValue;              // 0x0020(0x0010)()
	class FText                                   CallFunc_MakeLiteralText_ReturnValue_1;            // 0x0030(0x0010)()
	class FText                                   CallFunc_MakeLiteralText_ReturnValue_2;            // 0x0040(0x0010)()
	class FText                                   CallFunc_MakeLiteralText_ReturnValue_3;            // 0x0050(0x0010)()
	struct FSoundHandle                           CallFunc_SoundPlay_ReturnValue;                    // 0x0060(0x0004)()
	bool                                          CallFunc_IsGhostDataError_ReturnValue;             // 0x0064(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_65[0x3];                                       // 0x0065(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetUploadMaxCount_ReturnValue;            // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x006C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6D[0x3];                                       // 0x006D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_Select_Default;                             // 0x0070(0x0010)(ConstParm)
	bool                                          CallFunc_StartUpload_ReturnValue;                  // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GhostResultUploadActor_C_StartUpload) == 0x000008, "Wrong alignment on BP_GhostResultUploadActor_C_StartUpload");
static_assert(sizeof(BP_GhostResultUploadActor_C_StartUpload) == 0x000088, "Wrong size on BP_GhostResultUploadActor_C_StartUpload");
static_assert(offsetof(BP_GhostResultUploadActor_C_StartUpload, CallFunc_MakeLiteralByte_ReturnValue) == 0x000000, "Member 'BP_GhostResultUploadActor_C_StartUpload::CallFunc_MakeLiteralByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_StartUpload, CallFunc_Create_ReturnValue) == 0x000008, "Member 'BP_GhostResultUploadActor_C_StartUpload::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_StartUpload, CallFunc_Conv_ByteToInt_ReturnValue) == 0x000010, "Member 'BP_GhostResultUploadActor_C_StartUpload::CallFunc_Conv_ByteToInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_StartUpload, CallFunc_GetTimeTrialCurrentStageVersion_ReturnValue) == 0x000014, "Member 'BP_GhostResultUploadActor_C_StartUpload::CallFunc_GetTimeTrialCurrentStageVersion_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_StartUpload, CallFunc_IsUserHasNetworkRankingPrivilege_ReturnValue) == 0x000018, "Member 'BP_GhostResultUploadActor_C_StartUpload::CallFunc_IsUserHasNetworkRankingPrivilege_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_StartUpload, CallFunc_MakeLiteralText_ReturnValue) == 0x000020, "Member 'BP_GhostResultUploadActor_C_StartUpload::CallFunc_MakeLiteralText_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_StartUpload, CallFunc_MakeLiteralText_ReturnValue_1) == 0x000030, "Member 'BP_GhostResultUploadActor_C_StartUpload::CallFunc_MakeLiteralText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_StartUpload, CallFunc_MakeLiteralText_ReturnValue_2) == 0x000040, "Member 'BP_GhostResultUploadActor_C_StartUpload::CallFunc_MakeLiteralText_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_StartUpload, CallFunc_MakeLiteralText_ReturnValue_3) == 0x000050, "Member 'BP_GhostResultUploadActor_C_StartUpload::CallFunc_MakeLiteralText_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_StartUpload, CallFunc_SoundPlay_ReturnValue) == 0x000060, "Member 'BP_GhostResultUploadActor_C_StartUpload::CallFunc_SoundPlay_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_StartUpload, CallFunc_IsGhostDataError_ReturnValue) == 0x000064, "Member 'BP_GhostResultUploadActor_C_StartUpload::CallFunc_IsGhostDataError_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_StartUpload, CallFunc_GetUploadMaxCount_ReturnValue) == 0x000068, "Member 'BP_GhostResultUploadActor_C_StartUpload::CallFunc_GetUploadMaxCount_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_StartUpload, Temp_bool_Variable) == 0x00006C, "Member 'BP_GhostResultUploadActor_C_StartUpload::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_StartUpload, K2Node_Select_Default) == 0x000070, "Member 'BP_GhostResultUploadActor_C_StartUpload::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_StartUpload, CallFunc_StartUpload_ReturnValue) == 0x000080, "Member 'BP_GhostResultUploadActor_C_StartUpload::CallFunc_StartUpload_ReturnValue' has a wrong offset!");

// Function BP_GhostResultUploadActor.BP_GhostResultUploadActor_C.TimeTrialErrorWindow_OnDecide
// 0x0010 (0x0010 - 0x0000)
struct BP_GhostResultUploadActor_C_TimeTrialErrorWindow_OnDecide final
{
public:
	class UUnionUIButtonBase*                     Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         PanelIndex;                                        // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ButtonIndex;                                       // 0x000C(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GhostResultUploadActor_C_TimeTrialErrorWindow_OnDecide) == 0x000008, "Wrong alignment on BP_GhostResultUploadActor_C_TimeTrialErrorWindow_OnDecide");
static_assert(sizeof(BP_GhostResultUploadActor_C_TimeTrialErrorWindow_OnDecide) == 0x000010, "Wrong size on BP_GhostResultUploadActor_C_TimeTrialErrorWindow_OnDecide");
static_assert(offsetof(BP_GhostResultUploadActor_C_TimeTrialErrorWindow_OnDecide, Button) == 0x000000, "Member 'BP_GhostResultUploadActor_C_TimeTrialErrorWindow_OnDecide::Button' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_TimeTrialErrorWindow_OnDecide, PanelIndex) == 0x000008, "Member 'BP_GhostResultUploadActor_C_TimeTrialErrorWindow_OnDecide::PanelIndex' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_TimeTrialErrorWindow_OnDecide, ButtonIndex) == 0x00000C, "Member 'BP_GhostResultUploadActor_C_TimeTrialErrorWindow_OnDecide::ButtonIndex' has a wrong offset!");

// Function BP_GhostResultUploadActor.BP_GhostResultUploadActor_C.UploadCompleteEvent
// 0x0002 (0x0002 - 0x0000)
struct BP_GhostResultUploadActor_C_UploadCompleteEvent final
{
public:
	bool                                          IsError;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EUploadState                                  UploadState;                                       // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GhostResultUploadActor_C_UploadCompleteEvent) == 0x000001, "Wrong alignment on BP_GhostResultUploadActor_C_UploadCompleteEvent");
static_assert(sizeof(BP_GhostResultUploadActor_C_UploadCompleteEvent) == 0x000002, "Wrong size on BP_GhostResultUploadActor_C_UploadCompleteEvent");
static_assert(offsetof(BP_GhostResultUploadActor_C_UploadCompleteEvent, IsError) == 0x000000, "Member 'BP_GhostResultUploadActor_C_UploadCompleteEvent::IsError' has a wrong offset!");
static_assert(offsetof(BP_GhostResultUploadActor_C_UploadCompleteEvent, UploadState) == 0x000001, "Member 'BP_GhostResultUploadActor_C_UploadCompleteEvent::UploadState' has a wrong offset!");

}

