#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ItemBoxInstanceDomain1

#include "Basic.hpp"

#include "UnionRun_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ItemBoxInstanceDomain1.BP_ItemBoxInstanceDomain1_C
// 0x0000 (0x0470 - 0x0470)
class ABP_ItemBoxInstanceDomain1_C final : public AItemBoxInstanceObject
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ItemBoxInstanceDomain1_C">();
	}
	static class ABP_ItemBoxInstanceDomain1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ItemBoxInstanceDomain1_C>();
	}
};
static_assert(alignof(ABP_ItemBoxInstanceDomain1_C) == 0x000010, "Wrong alignment on ABP_ItemBoxInstanceDomain1_C");
static_assert(sizeof(ABP_ItemBoxInstanceDomain1_C) == 0x000470, "Wrong size on ABP_ItemBoxInstanceDomain1_C");

}

