#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_MenuStateGrandPrix

#include "Basic.hpp"

#include "UNION_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPC_MenuStateGrandPrix.BPC_MenuStateGrandPrix_C
// 0x0008 (0x0140 - 0x0138)
class UBPC_MenuStateGrandPrix_C final : public UMenuSequenceStateBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0138(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BPC_MenuStateGrandPrix(int32 EntryPoint);
	void OnExitState();
	void OnInitState();
	void OnUpdateState(float InDeltaTime);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPC_MenuStateGrandPrix_C">();
	}
	static class UBPC_MenuStateGrandPrix_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPC_MenuStateGrandPrix_C>();
	}
};
static_assert(alignof(UBPC_MenuStateGrandPrix_C) == 0x000008, "Wrong alignment on UBPC_MenuStateGrandPrix_C");
static_assert(sizeof(UBPC_MenuStateGrandPrix_C) == 0x000140, "Wrong size on UBPC_MenuStateGrandPrix_C");
static_assert(offsetof(UBPC_MenuStateGrandPrix_C, UberGraphFrame) == 0x000138, "Member 'UBPC_MenuStateGrandPrix_C::UberGraphFrame' has a wrong offset!");

}

