#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Drone_Text

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Drone_Text.WBP_Drone_Text_C
// 0x0010 (0x02F0 - 0x02E0)
class UWBP_Drone_Text_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 PAT_DroneText_Float;                               // 0x02E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_Drone_Text(int32 EntryPoint);
	void Set_Moniter_Meterial_Index(double Index_0);
	void Set_Moniter_Meterial_Reverse(bool Is_Reverse);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Drone_Text_C">();
	}
	static class UWBP_Drone_Text_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Drone_Text_C>();
	}
};
static_assert(alignof(UWBP_Drone_Text_C) == 0x000008, "Wrong alignment on UWBP_Drone_Text_C");
static_assert(sizeof(UWBP_Drone_Text_C) == 0x0002F0, "Wrong size on UWBP_Drone_Text_C");
static_assert(offsetof(UWBP_Drone_Text_C, UberGraphFrame) == 0x0002E0, "Member 'UWBP_Drone_Text_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_Drone_Text_C, PAT_DroneText_Float) == 0x0002E8, "Member 'UWBP_Drone_Text_C::PAT_DroneText_Float' has a wrong offset!");

}

