#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TopMenu

#include "Basic.hpp"

#include "UNION_structs.hpp"
#include "UnionSystem_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function WBP_TopMenu.WBP_TopMenu_C.BackFocuｓEvent
// 0x0008 (0x0008 - 0x0000)
struct WBP_TopMenu_C_BackFocuｓEvent final
{
public:
	class UUnionUIButtonsPanel*                   ButtonsPanel;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TopMenu_C_BackFocuｓEvent) == 0x000008, "Wrong alignment on WBP_TopMenu_C_BackFocuｓEvent");
static_assert(sizeof(WBP_TopMenu_C_BackFocuｓEvent) == 0x000008, "Wrong size on WBP_TopMenu_C_BackFocuｓEvent");
static_assert(offsetof(WBP_TopMenu_C_BackFocuｓEvent, ButtonsPanel) == 0x000000, "Member 'WBP_TopMenu_C_BackFocuｓEvent::ButtonsPanel' has a wrong offset!");

// Function WBP_TopMenu.WBP_TopMenu_C.Button Setting
// 0x0020 (0x0020 - 0x0000)
struct WBP_TopMenu_C_Button_Setting final
{
public:
	class UCommonMenuSubMenu*                     Sub_Menu;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECommonMenuButtonType                         Temp_byte_Variable;                                // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECommonMenuButtonType                         Temp_byte_Variable_1;                              // 0x000A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETopMenuPlayMode                              CallFunc_GetSelectedTopMenuPlayMode_ReturnValue;   // 0x000B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECommonMenuButtonType                         K2Node_Select_Default;                             // 0x000D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E[0x2];                                        // 0x000E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<ECommonMenuButtonType>                 K2Node_MakeArray_Array;                            // 0x0010(0x0010)(ConstParm, ReferenceParm)
};
static_assert(alignof(WBP_TopMenu_C_Button_Setting) == 0x000008, "Wrong alignment on WBP_TopMenu_C_Button_Setting");
static_assert(sizeof(WBP_TopMenu_C_Button_Setting) == 0x000020, "Wrong size on WBP_TopMenu_C_Button_Setting");
static_assert(offsetof(WBP_TopMenu_C_Button_Setting, Sub_Menu) == 0x000000, "Member 'WBP_TopMenu_C_Button_Setting::Sub_Menu' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_Button_Setting, Temp_bool_Variable) == 0x000008, "Member 'WBP_TopMenu_C_Button_Setting::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_Button_Setting, Temp_byte_Variable) == 0x000009, "Member 'WBP_TopMenu_C_Button_Setting::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_Button_Setting, Temp_byte_Variable_1) == 0x00000A, "Member 'WBP_TopMenu_C_Button_Setting::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_Button_Setting, CallFunc_GetSelectedTopMenuPlayMode_ReturnValue) == 0x00000B, "Member 'WBP_TopMenu_C_Button_Setting::CallFunc_GetSelectedTopMenuPlayMode_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_Button_Setting, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x00000C, "Member 'WBP_TopMenu_C_Button_Setting::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_Button_Setting, K2Node_Select_Default) == 0x00000D, "Member 'WBP_TopMenu_C_Button_Setting::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_Button_Setting, K2Node_MakeArray_Array) == 0x000010, "Member 'WBP_TopMenu_C_Button_Setting::K2Node_MakeArray_Array' has a wrong offset!");

// Function WBP_TopMenu.WBP_TopMenu_C.ExecuteUbergraph_WBP_TopMenu
// 0x0420 (0x0420 - 0x0000)
struct WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUnionUIButtonBase*                     K2Node_CustomEvent_Button;                         // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_PanelIndex;                     // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_ButtonIndex;                    // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETopMenuPlayMode                              Temp_byte_Variable;                                // 0x0029(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2A[0x2];                                       // 0x002A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_2;                  // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_True_if_break_was_hit_Variable_1;        // 0x003C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3D[0x3];                                       // 0x003D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x0044(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_45[0x3];                                       // 0x0045(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable_2;                   // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4C[0x4];                                       // 0x004C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	const class UTopMenuPlayModeButton*           Temp_object_Variable;                              // 0x0050(0x0008)(ConstParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_3;                   // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_3;                  // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_True_if_break_was_hit_Variable_2;        // 0x0064(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_65[0x3];                                       // 0x0065(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable_4;                   // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_2;                // 0x006C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6D[0x3];                                       // 0x006D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	const class UTopMenuPlayModeButton*           Temp_object_Variable_1;                            // 0x0070(0x0008)(ConstParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_MakeLiteralInt_ReturnValue;               // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_MakeLiteralBool_ReturnValue;              // 0x007C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7D[0x3];                                       // 0x007D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class UUnionUIButtonBase* Button, int32 ButtonIndex)> K2Node_CreateDelegate_OutputDelegate; // 0x0080(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetLastFocusedButton_OutLastFocusedButtonIndex; // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_94[0x4];                                       // 0x0094(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUnionUIButtonBase*                     CallFunc_GetLastFocusedButton_ReturnValue;         // 0x0098(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UUnionUIButtonBase* Button, int32 ButtonIndex)> K2Node_CreateDelegate_OutputDelegate_1; // 0x00A0(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UTopMenuPlayModeButton*                 K2Node_DynamicCast_AsTop_Menu_Play_Mode_Button;    // 0x00B0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B9[0x7];                                       // 0x00B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUnionUIButtonBase*                     K2Node_CustomEvent_Button_2;                       // 0x00C0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_ButtonIndex_2;                  // 0x00C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETopMenuPlayMode                              Temp_byte_Variable_1;                              // 0x00CC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_CD[0x3];                                       // 0x00CD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UUnionUIButtonsPanel*                   CallFunc_SetupButtonsPanel_ReturnValue;            // 0x00D0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetLastFocusedButton_OutLastFocusedButtonIndex_1; // 0x00D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DC[0x4];                                       // 0x00DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUserWidget*                            CallFunc_GetLastFocusedButton_ReturnValue_1;       // 0x00E0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UTopMenuPlayModeButton*                 K2Node_DynamicCast_AsTop_Menu_Play_Mode_Button_1;  // 0x00E8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F1[0x3];                                       // 0x00F1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable_4;                  // 0x00F4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_4;                 // 0x00F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00FC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_FD[0x3];                                       // 0x00FD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<ETopMenuPlayMode>                      K2Node_Event_TopMenuPlayModeArr;                   // 0x0100(0x0010)(ConstParm, ReferenceParm)
	int32                                         CallFunc_MakeLiteralInt_ReturnValue_1;             // 0x0110(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETopMenuPlayMode                              CallFunc_Array_Get_Item;                           // 0x0114(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_115[0x3];                                      // 0x0115(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0118(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x011C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_Contains_ReturnValue;               // 0x011D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_MakeLiteralBool_ReturnValue_1;            // 0x011E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETopMenuSequenceState                         K2Node_Event_PrevState_1;                          // 0x011F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECommonMenuButtonType                         CallFunc_CalcTopMenuSequenceSubMenuToCommonMenuButtonType_ReturnValue; // 0x0120(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CalcTopMenuSequenceSubMenu_ReturnValue;   // 0x0121(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_122[0x2];                                      // 0x0122(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class UUnionUIButtonBase* Button, int32 PanelIndex, int32 ButtonIndex)> K2Node_CreateDelegate_OutputDelegate_2; // 0x0124(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_134[0x4];                                      // 0x0134(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUnionUIButtonsPanel*                   CallFunc_SetupButtonsPanel_ReturnValue_1;          // 0x0138(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_3;            // 0x0140(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUnionUIButtonBase*                     CallFunc_Array_Get_Item_1;                         // 0x0150(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_LastIndex_ReturnValue;              // 0x0158(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_15C[0x4];                                      // 0x015C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUnionUIButtonBase*                     CallFunc_Array_Get_Item_2;                         // 0x0160(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Temp_object_Variable_2;                            // 0x0168(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	const class UTopMenuPlayModeButton*           K2Node_Select_Default;                             // 0x0170(0x0008)(ConstParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x0178(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_17C[0x4];                                      // 0x017C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidgetAnimation*                       Temp_object_Variable_3;                            // 0x0180(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Temp_object_Variable_4;                            // 0x0188(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Temp_object_Variable_5;                            // 0x0190(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Temp_object_Variable_6;                            // 0x0198(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UUnionUIButtonBase* Button, int32 PanelIndex, int32 ButtonIndex)> K2Node_CreateDelegate_OutputDelegate_4; // 0x01A0(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Temp_object_Variable_7;                            // 0x01B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Temp_object_Variable_8;                            // 0x01B8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	EMilestoneVersion                             CallFunc_GetMileStoneVersion_ReturnValue;          // 0x01C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x01C1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C2[0x6];                                      // 0x01C2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidgetAnimation*                       Temp_object_Variable_9;                            // 0x01C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x01D0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue_1;            // 0x01D8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Temp_object_Variable_10;                           // 0x01E0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Temp_object_Variable_11;                           // 0x01E8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Temp_object_Variable_12;                           // 0x01F0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Temp_object_Variable_13;                           // 0x01F8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Temp_object_Variable_14;                           // 0x0200(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Temp_object_Variable_15;                           // 0x0208(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Temp_object_Variable_16;                           // 0x0210(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Temp_object_Variable_17;                           // 0x0218(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	ETopMenuPlayMode                              K2Node_Event_PlayMode_2;                           // 0x0220(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETopMenuPlayMode                              K2Node_Event_PlayMode_1;                           // 0x0221(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETopMenuPlayMode                              K2Node_Event_PlayMode;                             // 0x0222(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_223[0x5];                                      // 0x0223(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<ETopMenuGameMode>                      K2Node_Event_BeltButtonTypeArr;                    // 0x0228(0x0010)(ConstParm, ReferenceParm)
	ETopMenuSequenceState                         K2Node_Event_PrevState;                            // 0x0238(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECommonMenuButtonType                         CallFunc_CalcTopMenuSequenceSubMenuToCommonMenuButtonType_ReturnValue_1; // 0x0239(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CalcTopMenuSequenceSubMenu_ReturnValue_1; // 0x023A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_23B[0x1];                                      // 0x023B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_MakeLiteralInt_ReturnValue_2;             // 0x023C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_MakeLiteralBool_ReturnValue_2;            // 0x0240(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0241(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_242[0x6];                                      // 0x0242(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidgetAnimation*                       Temp_object_Variable_18;                           // 0x0248(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_5;                  // 0x0250(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_5;                 // 0x0254(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Temp_object_Variable_19;                           // 0x0258(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Temp_object_Variable_20;                           // 0x0260(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUnionUIButtonBase*                     CallFunc_Array_Get_Item_3;                         // 0x0268(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_LastIndex_ReturnValue_1;            // 0x0270(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_274[0x4];                                      // 0x0274(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidgetAnimation*                       Temp_object_Variable_21;                           // 0x0278(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUnionUIButtonBase*                     CallFunc_Array_Get_Item_4;                         // 0x0280(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	ETopMenuSequenceState                         Temp_byte_Variable_2;                              // 0x0288(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_289[0x3];                                      // 0x0289(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class UUnionUIButtonBase* Button, int32 PanelIndex, int32 ButtonIndex)> K2Node_CreateDelegate_OutputDelegate_5; // 0x028C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UUnionUIButtonBase* Button, int32 PanelIndex, int32 ButtonIndex)> K2Node_CreateDelegate_OutputDelegate_6; // 0x029C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_5;                   // 0x02AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue_2;            // 0x02B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	ETopMenuSequenceState                         K2Node_Event_InitState;                            // 0x02B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2B9[0x3];                                      // 0x02B9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_7;            // 0x02BC(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x02CC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2CD[0x3];                                      // 0x02CD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UUnionUIButtonBase*                     CallFunc_Array_Get_Item_5;                         // 0x02D0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x02D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x02DC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x02DD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2DE[0x2];                                      // 0x02DE(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<ETopMenuPlayMode>                      K2Node_MakeArray_Array;                            // 0x02E0(0x0010)(ConstParm, ReferenceParm)
	ECrossplayPlatform                            CallFunc_GetPlatformGroup_ReturnValue;             // 0x02F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2F1[0x7];                                      // 0x02F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<ETopMenuPlayMode>                      K2Node_MakeArray_Array_1;                          // 0x02F8(0x0010)(ConstParm, ReferenceParm)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_2;        // 0x0308(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0309(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_30A[0x6];                                      // 0x030A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue_3;            // 0x0310(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue_4;            // 0x0318(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x0320(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0321(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_322[0x6];                                      // 0x0322(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<ETopMenuPlayMode>                      K2Node_Select_Default_1;                           // 0x0328(0x0010)(ConstParm, ReferenceParm)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x0338(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_339[0x7];                                      // 0x0339(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUnionUIButtonsPanel*                   K2Node_CustomEvent_ButtonsPanel;                   // 0x0340(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetLastFocusedButton_OutLastFocusedButtonIndex_2; // 0x0348(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_34C[0x4];                                      // 0x034C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUnionUIButtonBase*                     CallFunc_GetLastFocusedButton_ReturnValue_2;       // 0x0350(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_CustomEvent_Visibility;                     // 0x0358(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETopMenuSequenceState                         K2Node_CustomEvent_BackState;                      // 0x0359(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_5;                    // 0x035A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x035B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35C[0x4];                                      // 0x035C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMenuWorldSubsystem*                    CallFunc_GetWorldSubsystem_ReturnValue;            // 0x0360(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUnionUIButtonBase*                     CallFunc_Array_Get_Item_6;                         // 0x0368(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UTopMenuPlayerNumButton*                K2Node_DynamicCast_AsTop_Menu_Player_Num_Button;   // 0x0370(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0378(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_379[0x3];                                      // 0x0379(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x037C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x0380(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_381[0x7];                                      // 0x0381(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTopMenuPlayModeButton*                 CallFunc_Array_Get_Item_7;                         // 0x0388(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0390(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_391[0x3];                                      // 0x0391(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue_3;               // 0x0394(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_3;                // 0x0398(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0399(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_6;                    // 0x039A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_7;                    // 0x039B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39C[0x4];                                      // 0x039C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonMenuButtonBase*                  CallFunc_Array_Get_Item_8;                         // 0x03A0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_4;               // 0x03A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_4;                // 0x03AC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x03AD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_3;        // 0x03AE(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3AF[0x1];                                      // 0x03AF(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_CreatePlayAnimationTimeRangeProxyObject_Result; // 0x03B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimationPlayCallbackProxy*      CallFunc_CreatePlayAnimationTimeRangeProxyObject_ReturnValue; // 0x03B8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_8;                    // 0x03C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_9;                    // 0x03C1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C2[0x6];                                      // 0x03C2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidgetAnimation*                       K2Node_Select_Default_2;                           // 0x03C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_CreatePlayAnimationTimeRangeProxyObject_Result_1; // 0x03D0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimationPlayCallbackProxy*      CallFunc_CreatePlayAnimationTimeRangeProxyObject_ReturnValue_1; // 0x03D8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_10;                   // 0x03E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3E1[0x7];                                      // 0x03E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUnionUIButtonsPanel*                   CallFunc_SetupButtonsPanel_ReturnValue_2;          // 0x03E8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AAppPlayerController*                   CallFunc_GetAppPlayerController_ReturnValue;       // 0x03F0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_11;                   // 0x03F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_12;                   // 0x03F9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3FA[0x6];                                      // 0x03FA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonMenuButtonBase*                  CallFunc_Array_Get_Item_9;                         // 0x0400(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_5;               // 0x0408(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_5;                // 0x040C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_2;                 // 0x040D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_4;        // 0x040E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_40F[0x1];                                      // 0x040F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class UUnionUIButtonBase*                     K2Node_CustomEvent_Button_1;                       // 0x0410(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_PanelIndex_1;                   // 0x0418(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_ButtonIndex_1;                  // 0x041C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu) == 0x000008, "Wrong alignment on WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu");
static_assert(sizeof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu) == 0x000420, "Wrong size on WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, EntryPoint) == 0x000000, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_CustomEvent_Button) == 0x000008, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_CustomEvent_Button' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_CustomEvent_PanelIndex) == 0x000010, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_CustomEvent_PanelIndex' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_CustomEvent_ButtonIndex) == 0x000014, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_CustomEvent_ButtonIndex' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_int_Loop_Counter_Variable) == 0x000018, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Add_IntInt_ReturnValue) == 0x00001C, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_bool_True_if_break_was_hit_Variable) == 0x000020, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_bool_True_if_break_was_hit_Variable' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_int_Array_Index_Variable) == 0x000024, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Not_PreBool_ReturnValue) == 0x000028, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_byte_Variable) == 0x000029, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_int_Loop_Counter_Variable_1) == 0x00002C, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_int_Loop_Counter_Variable_2) == 0x000030, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_int_Loop_Counter_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Add_IntInt_ReturnValue_1) == 0x000034, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Add_IntInt_ReturnValue_2) == 0x000038, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_bool_True_if_break_was_hit_Variable_1) == 0x00003C, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_bool_True_if_break_was_hit_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_int_Array_Index_Variable_1) == 0x000040, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Not_PreBool_ReturnValue_1) == 0x000044, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Not_PreBool_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_int_Array_Index_Variable_2) == 0x000048, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_int_Array_Index_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_object_Variable) == 0x000050, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_int_Array_Index_Variable_3) == 0x000058, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_int_Array_Index_Variable_3' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_int_Loop_Counter_Variable_3) == 0x00005C, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_int_Loop_Counter_Variable_3' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Add_IntInt_ReturnValue_3) == 0x000060, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_bool_True_if_break_was_hit_Variable_2) == 0x000064, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_bool_True_if_break_was_hit_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_int_Array_Index_Variable_4) == 0x000068, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_int_Array_Index_Variable_4' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Not_PreBool_ReturnValue_2) == 0x00006C, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Not_PreBool_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_object_Variable_1) == 0x000070, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_object_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_MakeLiteralInt_ReturnValue) == 0x000078, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_MakeLiteralInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_MakeLiteralBool_ReturnValue) == 0x00007C, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_MakeLiteralBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_CreateDelegate_OutputDelegate) == 0x000080, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_GetLastFocusedButton_OutLastFocusedButtonIndex) == 0x000090, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_GetLastFocusedButton_OutLastFocusedButtonIndex' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_GetLastFocusedButton_ReturnValue) == 0x000098, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_GetLastFocusedButton_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_CreateDelegate_OutputDelegate_1) == 0x0000A0, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_DynamicCast_AsTop_Menu_Play_Mode_Button) == 0x0000B0, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_DynamicCast_AsTop_Menu_Play_Mode_Button' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_DynamicCast_bSuccess) == 0x0000B8, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_CustomEvent_Button_2) == 0x0000C0, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_CustomEvent_Button_2' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_CustomEvent_ButtonIndex_2) == 0x0000C8, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_CustomEvent_ButtonIndex_2' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_byte_Variable_1) == 0x0000CC, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_SetupButtonsPanel_ReturnValue) == 0x0000D0, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_SetupButtonsPanel_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_GetLastFocusedButton_OutLastFocusedButtonIndex_1) == 0x0000D8, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_GetLastFocusedButton_OutLastFocusedButtonIndex_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_GetLastFocusedButton_ReturnValue_1) == 0x0000E0, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_GetLastFocusedButton_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_DynamicCast_AsTop_Menu_Play_Mode_Button_1) == 0x0000E8, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_DynamicCast_AsTop_Menu_Play_Mode_Button_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_DynamicCast_bSuccess_1) == 0x0000F0, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_int_Loop_Counter_Variable_4) == 0x0000F4, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_int_Loop_Counter_Variable_4' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Add_IntInt_ReturnValue_4) == 0x0000F8, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Add_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_IsValid_ReturnValue) == 0x0000FC, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_Event_TopMenuPlayModeArr) == 0x000100, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_Event_TopMenuPlayModeArr' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_MakeLiteralInt_ReturnValue_1) == 0x000110, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_MakeLiteralInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Array_Get_Item) == 0x000114, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Array_Length_ReturnValue) == 0x000118, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Less_IntInt_ReturnValue) == 0x00011C, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Array_Contains_ReturnValue) == 0x00011D, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Array_Contains_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_MakeLiteralBool_ReturnValue_1) == 0x00011E, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_MakeLiteralBool_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_Event_PrevState_1) == 0x00011F, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_Event_PrevState_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_CalcTopMenuSequenceSubMenuToCommonMenuButtonType_ReturnValue) == 0x000120, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_CalcTopMenuSequenceSubMenuToCommonMenuButtonType_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_CalcTopMenuSequenceSubMenu_ReturnValue) == 0x000121, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_CalcTopMenuSequenceSubMenu_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_CreateDelegate_OutputDelegate_2) == 0x000124, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_SetupButtonsPanel_ReturnValue_1) == 0x000138, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_SetupButtonsPanel_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_CreateDelegate_OutputDelegate_3) == 0x000140, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Array_Get_Item_1) == 0x000150, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Array_LastIndex_ReturnValue) == 0x000158, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Array_LastIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Array_Get_Item_2) == 0x000160, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_object_Variable_2) == 0x000168, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_object_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_Select_Default) == 0x000170, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Array_Add_ReturnValue) == 0x000178, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_object_Variable_3) == 0x000180, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_object_Variable_3' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_object_Variable_4) == 0x000188, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_object_Variable_4' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_object_Variable_5) == 0x000190, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_object_Variable_5' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_object_Variable_6) == 0x000198, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_object_Variable_6' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_CreateDelegate_OutputDelegate_4) == 0x0001A0, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_object_Variable_7) == 0x0001B0, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_object_Variable_7' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_object_Variable_8) == 0x0001B8, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_object_Variable_8' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_GetMileStoneVersion_ReturnValue) == 0x0001C0, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_GetMileStoneVersion_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x0001C1, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_object_Variable_9) == 0x0001C8, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_object_Variable_9' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_GetOwningPlayer_ReturnValue) == 0x0001D0, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_GetOwningPlayer_ReturnValue_1) == 0x0001D8, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_GetOwningPlayer_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_object_Variable_10) == 0x0001E0, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_object_Variable_10' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_object_Variable_11) == 0x0001E8, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_object_Variable_11' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_object_Variable_12) == 0x0001F0, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_object_Variable_12' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_object_Variable_13) == 0x0001F8, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_object_Variable_13' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_object_Variable_14) == 0x000200, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_object_Variable_14' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_object_Variable_15) == 0x000208, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_object_Variable_15' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_object_Variable_16) == 0x000210, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_object_Variable_16' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_object_Variable_17) == 0x000218, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_object_Variable_17' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_Event_PlayMode_2) == 0x000220, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_Event_PlayMode_2' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_Event_PlayMode_1) == 0x000221, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_Event_PlayMode_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_Event_PlayMode) == 0x000222, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_Event_PlayMode' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_Event_BeltButtonTypeArr) == 0x000228, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_Event_BeltButtonTypeArr' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_Event_PrevState) == 0x000238, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_Event_PrevState' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_CalcTopMenuSequenceSubMenuToCommonMenuButtonType_ReturnValue_1) == 0x000239, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_CalcTopMenuSequenceSubMenuToCommonMenuButtonType_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_CalcTopMenuSequenceSubMenu_ReturnValue_1) == 0x00023A, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_CalcTopMenuSequenceSubMenu_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_MakeLiteralInt_ReturnValue_2) == 0x00023C, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_MakeLiteralInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_MakeLiteralBool_ReturnValue_2) == 0x000240, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_MakeLiteralBool_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_IsValid_ReturnValue_1) == 0x000241, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_object_Variable_18) == 0x000248, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_object_Variable_18' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_int_Loop_Counter_Variable_5) == 0x000250, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_int_Loop_Counter_Variable_5' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Add_IntInt_ReturnValue_5) == 0x000254, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Add_IntInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_object_Variable_19) == 0x000258, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_object_Variable_19' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_object_Variable_20) == 0x000260, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_object_Variable_20' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Array_Get_Item_3) == 0x000268, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Array_Get_Item_3' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Array_LastIndex_ReturnValue_1) == 0x000270, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Array_LastIndex_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_object_Variable_21) == 0x000278, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_object_Variable_21' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Array_Get_Item_4) == 0x000280, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Array_Get_Item_4' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_byte_Variable_2) == 0x000288, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_byte_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_CreateDelegate_OutputDelegate_5) == 0x00028C, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_CreateDelegate_OutputDelegate_5' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_CreateDelegate_OutputDelegate_6) == 0x00029C, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_CreateDelegate_OutputDelegate_6' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_int_Array_Index_Variable_5) == 0x0002AC, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_int_Array_Index_Variable_5' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_GetOwningPlayer_ReturnValue_2) == 0x0002B0, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_GetOwningPlayer_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_Event_InitState) == 0x0002B8, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_Event_InitState' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_CreateDelegate_OutputDelegate_7) == 0x0002BC, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_CreateDelegate_OutputDelegate_7' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_IsValid_ReturnValue_2) == 0x0002CC, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Array_Get_Item_5) == 0x0002D0, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Array_Get_Item_5' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Array_Length_ReturnValue_1) == 0x0002D8, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Less_IntInt_ReturnValue_1) == 0x0002DC, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_EqualEqual_ByteByte_ReturnValue_1) == 0x0002DD, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_EqualEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_MakeArray_Array) == 0x0002E0, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_GetPlatformGroup_ReturnValue) == 0x0002F0, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_GetPlatformGroup_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_MakeArray_Array_1) == 0x0002F8, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_MakeArray_Array_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_EqualEqual_ByteByte_ReturnValue_2) == 0x000308, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_EqualEqual_ByteByte_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_BooleanOR_ReturnValue) == 0x000309, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_GetOwningPlayer_ReturnValue_3) == 0x000310, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_GetOwningPlayer_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_GetOwningPlayer_ReturnValue_4) == 0x000318, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_GetOwningPlayer_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_IsValid_ReturnValue_3) == 0x000320, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, Temp_bool_Variable) == 0x000321, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_Select_Default_1) == 0x000328, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_IsValid_ReturnValue_4) == 0x000338, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_IsValid_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_CustomEvent_ButtonsPanel) == 0x000340, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_CustomEvent_ButtonsPanel' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_GetLastFocusedButton_OutLastFocusedButtonIndex_2) == 0x000348, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_GetLastFocusedButton_OutLastFocusedButtonIndex_2' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_GetLastFocusedButton_ReturnValue_2) == 0x000350, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_GetLastFocusedButton_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_CustomEvent_Visibility) == 0x000358, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_CustomEvent_Visibility' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_CustomEvent_BackState) == 0x000359, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_CustomEvent_BackState' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_IsValid_ReturnValue_5) == 0x00035A, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_IsValid_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_SwitchEnum_CmpSuccess) == 0x00035B, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_GetWorldSubsystem_ReturnValue) == 0x000360, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_GetWorldSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Array_Get_Item_6) == 0x000368, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Array_Get_Item_6' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_DynamicCast_AsTop_Menu_Player_Num_Button) == 0x000370, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_DynamicCast_AsTop_Menu_Player_Num_Button' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_DynamicCast_bSuccess_2) == 0x000378, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Array_Length_ReturnValue_2) == 0x00037C, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Array_Length_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Less_IntInt_ReturnValue_2) == 0x000380, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Less_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Array_Get_Item_7) == 0x000388, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Array_Get_Item_7' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000390, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Array_Length_ReturnValue_3) == 0x000394, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Array_Length_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Less_IntInt_ReturnValue_3) == 0x000398, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Less_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_BooleanAND_ReturnValue) == 0x000399, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_IsValid_ReturnValue_6) == 0x00039A, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_IsValid_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_IsValid_ReturnValue_7) == 0x00039B, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_IsValid_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Array_Get_Item_8) == 0x0003A0, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Array_Get_Item_8' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Array_Length_ReturnValue_4) == 0x0003A8, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Array_Length_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Less_IntInt_ReturnValue_4) == 0x0003AC, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Less_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_BooleanAND_ReturnValue_1) == 0x0003AD, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_EqualEqual_ByteByte_ReturnValue_3) == 0x0003AE, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_EqualEqual_ByteByte_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_CreatePlayAnimationTimeRangeProxyObject_Result) == 0x0003B0, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_CreatePlayAnimationTimeRangeProxyObject_Result' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_CreatePlayAnimationTimeRangeProxyObject_ReturnValue) == 0x0003B8, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_CreatePlayAnimationTimeRangeProxyObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_IsValid_ReturnValue_8) == 0x0003C0, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_IsValid_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_IsValid_ReturnValue_9) == 0x0003C1, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_IsValid_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_Select_Default_2) == 0x0003C8, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_Select_Default_2' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_CreatePlayAnimationTimeRangeProxyObject_Result_1) == 0x0003D0, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_CreatePlayAnimationTimeRangeProxyObject_Result_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_CreatePlayAnimationTimeRangeProxyObject_ReturnValue_1) == 0x0003D8, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_CreatePlayAnimationTimeRangeProxyObject_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_IsValid_ReturnValue_10) == 0x0003E0, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_IsValid_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_SetupButtonsPanel_ReturnValue_2) == 0x0003E8, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_SetupButtonsPanel_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_GetAppPlayerController_ReturnValue) == 0x0003F0, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_GetAppPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_IsValid_ReturnValue_11) == 0x0003F8, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_IsValid_ReturnValue_11' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_IsValid_ReturnValue_12) == 0x0003F9, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_IsValid_ReturnValue_12' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Array_Get_Item_9) == 0x000400, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Array_Get_Item_9' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Array_Length_ReturnValue_5) == 0x000408, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Array_Length_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_Less_IntInt_ReturnValue_5) == 0x00040C, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_Less_IntInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_BooleanAND_ReturnValue_2) == 0x00040D, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_BooleanAND_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, CallFunc_EqualEqual_ByteByte_ReturnValue_4) == 0x00040E, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::CallFunc_EqualEqual_ByteByte_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_CustomEvent_Button_1) == 0x000410, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_CustomEvent_Button_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_CustomEvent_PanelIndex_1) == 0x000418, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_CustomEvent_PanelIndex_1' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu, K2Node_CustomEvent_ButtonIndex_1) == 0x00041C, "Member 'WBP_TopMenu_C_ExecuteUbergraph_WBP_TopMenu::K2Node_CustomEvent_ButtonIndex_1' has a wrong offset!");

// Function WBP_TopMenu.WBP_TopMenu_C.InitializeGameMode
// 0x0020 (0x0020 - 0x0000)
struct WBP_TopMenu_C_InitializeGameMode final
{
public:
	ETopMenuPlayMode                              PlayMode;                                          // 0x0000(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<ETopMenuGameMode>                      BeltButtonTypeArr;                                 // 0x0008(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	ETopMenuSequenceState                         PrevState;                                         // 0x0018(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TopMenu_C_InitializeGameMode) == 0x000008, "Wrong alignment on WBP_TopMenu_C_InitializeGameMode");
static_assert(sizeof(WBP_TopMenu_C_InitializeGameMode) == 0x000020, "Wrong size on WBP_TopMenu_C_InitializeGameMode");
static_assert(offsetof(WBP_TopMenu_C_InitializeGameMode, PlayMode) == 0x000000, "Member 'WBP_TopMenu_C_InitializeGameMode::PlayMode' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_InitializeGameMode, BeltButtonTypeArr) == 0x000008, "Member 'WBP_TopMenu_C_InitializeGameMode::BeltButtonTypeArr' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_InitializeGameMode, PrevState) == 0x000018, "Member 'WBP_TopMenu_C_InitializeGameMode::PrevState' has a wrong offset!");

// Function WBP_TopMenu.WBP_TopMenu_C.InitializePlayMode
// 0x0001 (0x0001 - 0x0000)
struct WBP_TopMenu_C_InitializePlayMode final
{
public:
	ETopMenuSequenceState                         PrevState;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TopMenu_C_InitializePlayMode) == 0x000001, "Wrong alignment on WBP_TopMenu_C_InitializePlayMode");
static_assert(sizeof(WBP_TopMenu_C_InitializePlayMode) == 0x000001, "Wrong size on WBP_TopMenu_C_InitializePlayMode");
static_assert(offsetof(WBP_TopMenu_C_InitializePlayMode, PrevState) == 0x000000, "Member 'WBP_TopMenu_C_InitializePlayMode::PrevState' has a wrong offset!");

// Function WBP_TopMenu.WBP_TopMenu_C.InitializeTopMenu
// 0x0001 (0x0001 - 0x0000)
struct WBP_TopMenu_C_InitializeTopMenu final
{
public:
	ETopMenuSequenceState                         InitState;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TopMenu_C_InitializeTopMenu) == 0x000001, "Wrong alignment on WBP_TopMenu_C_InitializeTopMenu");
static_assert(sizeof(WBP_TopMenu_C_InitializeTopMenu) == 0x000001, "Wrong size on WBP_TopMenu_C_InitializeTopMenu");
static_assert(offsetof(WBP_TopMenu_C_InitializeTopMenu, InitState) == 0x000000, "Member 'WBP_TopMenu_C_InitializeTopMenu::InitState' has a wrong offset!");

// Function WBP_TopMenu.WBP_TopMenu_C.IsPlayerNumButtonAnimationPlaying
// 0x0028 (0x0028 - 0x0000)
struct WBP_TopMenu_C_IsPlayerNumButtonAnimationPlaying final
{
public:
	bool                                          PlayingAnimation;                                  // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsSkipSelectPlayNumMilestoneVersion_ReturnValue; // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_12[0x6];                                       // 0x0012(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UUnionUIButtonBase*                     CallFunc_Array_Get_Item;                           // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsPlayingAnimation_ReturnValue;           // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0025(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsAnimationPlaying_ReturnValue;           // 0x0026(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TopMenu_C_IsPlayerNumButtonAnimationPlaying) == 0x000008, "Wrong alignment on WBP_TopMenu_C_IsPlayerNumButtonAnimationPlaying");
static_assert(sizeof(WBP_TopMenu_C_IsPlayerNumButtonAnimationPlaying) == 0x000028, "Wrong size on WBP_TopMenu_C_IsPlayerNumButtonAnimationPlaying");
static_assert(offsetof(WBP_TopMenu_C_IsPlayerNumButtonAnimationPlaying, PlayingAnimation) == 0x000000, "Member 'WBP_TopMenu_C_IsPlayerNumButtonAnimationPlaying::PlayingAnimation' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_IsPlayerNumButtonAnimationPlaying, Temp_int_Array_Index_Variable) == 0x000004, "Member 'WBP_TopMenu_C_IsPlayerNumButtonAnimationPlaying::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_IsPlayerNumButtonAnimationPlaying, Temp_int_Loop_Counter_Variable) == 0x000008, "Member 'WBP_TopMenu_C_IsPlayerNumButtonAnimationPlaying::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_IsPlayerNumButtonAnimationPlaying, CallFunc_Add_IntInt_ReturnValue) == 0x00000C, "Member 'WBP_TopMenu_C_IsPlayerNumButtonAnimationPlaying::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_IsPlayerNumButtonAnimationPlaying, CallFunc_IsSkipSelectPlayNumMilestoneVersion_ReturnValue) == 0x000010, "Member 'WBP_TopMenu_C_IsPlayerNumButtonAnimationPlaying::CallFunc_IsSkipSelectPlayNumMilestoneVersion_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_IsPlayerNumButtonAnimationPlaying, CallFunc_IsValid_ReturnValue) == 0x000011, "Member 'WBP_TopMenu_C_IsPlayerNumButtonAnimationPlaying::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_IsPlayerNumButtonAnimationPlaying, CallFunc_Array_Get_Item) == 0x000018, "Member 'WBP_TopMenu_C_IsPlayerNumButtonAnimationPlaying::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_IsPlayerNumButtonAnimationPlaying, CallFunc_Array_Length_ReturnValue) == 0x000020, "Member 'WBP_TopMenu_C_IsPlayerNumButtonAnimationPlaying::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_IsPlayerNumButtonAnimationPlaying, CallFunc_IsPlayingAnimation_ReturnValue) == 0x000024, "Member 'WBP_TopMenu_C_IsPlayerNumButtonAnimationPlaying::CallFunc_IsPlayingAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_IsPlayerNumButtonAnimationPlaying, CallFunc_Less_IntInt_ReturnValue) == 0x000025, "Member 'WBP_TopMenu_C_IsPlayerNumButtonAnimationPlaying::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_IsPlayerNumButtonAnimationPlaying, CallFunc_IsAnimationPlaying_ReturnValue) == 0x000026, "Member 'WBP_TopMenu_C_IsPlayerNumButtonAnimationPlaying::CallFunc_IsAnimationPlaying_ReturnValue' has a wrong offset!");

// Function WBP_TopMenu.WBP_TopMenu_C.OnCancelSubMenu
// 0x0010 (0x0010 - 0x0000)
struct WBP_TopMenu_C_OnCancelSubMenu final
{
public:
	class UUnionUIButtonBase*                     Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         PanelIndex;                                        // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ButtonIndex;                                       // 0x000C(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TopMenu_C_OnCancelSubMenu) == 0x000008, "Wrong alignment on WBP_TopMenu_C_OnCancelSubMenu");
static_assert(sizeof(WBP_TopMenu_C_OnCancelSubMenu) == 0x000010, "Wrong size on WBP_TopMenu_C_OnCancelSubMenu");
static_assert(offsetof(WBP_TopMenu_C_OnCancelSubMenu, Button) == 0x000000, "Member 'WBP_TopMenu_C_OnCancelSubMenu::Button' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_OnCancelSubMenu, PanelIndex) == 0x000008, "Member 'WBP_TopMenu_C_OnCancelSubMenu::PanelIndex' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_OnCancelSubMenu, ButtonIndex) == 0x00000C, "Member 'WBP_TopMenu_C_OnCancelSubMenu::ButtonIndex' has a wrong offset!");

// Function WBP_TopMenu.WBP_TopMenu_C.OnDecisionSubMenu
// 0x0010 (0x0010 - 0x0000)
struct WBP_TopMenu_C_OnDecisionSubMenu final
{
public:
	class UUnionUIButtonBase*                     Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         PanelIndex;                                        // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ButtonIndex;                                       // 0x000C(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TopMenu_C_OnDecisionSubMenu) == 0x000008, "Wrong alignment on WBP_TopMenu_C_OnDecisionSubMenu");
static_assert(sizeof(WBP_TopMenu_C_OnDecisionSubMenu) == 0x000010, "Wrong size on WBP_TopMenu_C_OnDecisionSubMenu");
static_assert(offsetof(WBP_TopMenu_C_OnDecisionSubMenu, Button) == 0x000000, "Member 'WBP_TopMenu_C_OnDecisionSubMenu::Button' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_OnDecisionSubMenu, PanelIndex) == 0x000008, "Member 'WBP_TopMenu_C_OnDecisionSubMenu::PanelIndex' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_OnDecisionSubMenu, ButtonIndex) == 0x00000C, "Member 'WBP_TopMenu_C_OnDecisionSubMenu::ButtonIndex' has a wrong offset!");

// Function WBP_TopMenu.WBP_TopMenu_C.PlayAnimationNumActivePlayerNum
// 0x0010 (0x0010 - 0x0000)
struct WBP_TopMenu_C_PlayAnimationNumActivePlayerNum final
{
public:
	class UUnionUIButtonBase*                     Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         ButtonIndex;                                       // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TopMenu_C_PlayAnimationNumActivePlayerNum) == 0x000008, "Wrong alignment on WBP_TopMenu_C_PlayAnimationNumActivePlayerNum");
static_assert(sizeof(WBP_TopMenu_C_PlayAnimationNumActivePlayerNum) == 0x000010, "Wrong size on WBP_TopMenu_C_PlayAnimationNumActivePlayerNum");
static_assert(offsetof(WBP_TopMenu_C_PlayAnimationNumActivePlayerNum, Button) == 0x000000, "Member 'WBP_TopMenu_C_PlayAnimationNumActivePlayerNum::Button' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_PlayAnimationNumActivePlayerNum, ButtonIndex) == 0x000008, "Member 'WBP_TopMenu_C_PlayAnimationNumActivePlayerNum::ButtonIndex' has a wrong offset!");

// Function WBP_TopMenu.WBP_TopMenu_C.SetButtonVisible
// 0x0002 (0x0002 - 0x0000)
struct WBP_TopMenu_C_SetButtonVisible final
{
public:
	ESlateVisibility                              Visibility_0;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETopMenuSequenceState                         BackState;                                         // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TopMenu_C_SetButtonVisible) == 0x000001, "Wrong alignment on WBP_TopMenu_C_SetButtonVisible");
static_assert(sizeof(WBP_TopMenu_C_SetButtonVisible) == 0x000002, "Wrong size on WBP_TopMenu_C_SetButtonVisible");
static_assert(offsetof(WBP_TopMenu_C_SetButtonVisible, Visibility_0) == 0x000000, "Member 'WBP_TopMenu_C_SetButtonVisible::Visibility_0' has a wrong offset!");
static_assert(offsetof(WBP_TopMenu_C_SetButtonVisible, BackState) == 0x000001, "Member 'WBP_TopMenu_C_SetButtonVisible::BackState' has a wrong offset!");

// Function WBP_TopMenu.WBP_TopMenu_C.SetIconGameMode
// 0x0001 (0x0001 - 0x0000)
struct WBP_TopMenu_C_SetIconGameMode final
{
public:
	ETopMenuPlayMode                              PlayMode;                                          // 0x0000(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TopMenu_C_SetIconGameMode) == 0x000001, "Wrong alignment on WBP_TopMenu_C_SetIconGameMode");
static_assert(sizeof(WBP_TopMenu_C_SetIconGameMode) == 0x000001, "Wrong size on WBP_TopMenu_C_SetIconGameMode");
static_assert(offsetof(WBP_TopMenu_C_SetIconGameMode, PlayMode) == 0x000000, "Member 'WBP_TopMenu_C_SetIconGameMode::PlayMode' has a wrong offset!");

// Function WBP_TopMenu.WBP_TopMenu_C.SetTextGameModeTitle
// 0x0001 (0x0001 - 0x0000)
struct WBP_TopMenu_C_SetTextGameModeTitle final
{
public:
	ETopMenuPlayMode                              PlayMode;                                          // 0x0000(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TopMenu_C_SetTextGameModeTitle) == 0x000001, "Wrong alignment on WBP_TopMenu_C_SetTextGameModeTitle");
static_assert(sizeof(WBP_TopMenu_C_SetTextGameModeTitle) == 0x000001, "Wrong size on WBP_TopMenu_C_SetTextGameModeTitle");
static_assert(offsetof(WBP_TopMenu_C_SetTextGameModeTitle, PlayMode) == 0x000000, "Member 'WBP_TopMenu_C_SetTextGameModeTitle::PlayMode' has a wrong offset!");

// Function WBP_TopMenu.WBP_TopMenu_C.SetupPlayMode
// 0x0010 (0x0010 - 0x0000)
struct WBP_TopMenu_C_SetupPlayMode final
{
public:
	TArray<ETopMenuPlayMode>                      TopMenuPlayModeArr;                                // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(WBP_TopMenu_C_SetupPlayMode) == 0x000008, "Wrong alignment on WBP_TopMenu_C_SetupPlayMode");
static_assert(sizeof(WBP_TopMenu_C_SetupPlayMode) == 0x000010, "Wrong size on WBP_TopMenu_C_SetupPlayMode");
static_assert(offsetof(WBP_TopMenu_C_SetupPlayMode, TopMenuPlayModeArr) == 0x000000, "Member 'WBP_TopMenu_C_SetupPlayMode::TopMenuPlayModeArr' has a wrong offset!");

}

